/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Resource = {
  _type: "resource";
  type?: "repo" | "docs" | "pdf" | "link" | "asset";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  keyPoints?: Array<string>;
  proTip?: string;
  notes?: BlockContent;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level?:
    | "beginner"
    | "intermediate"
    | "advanced"
    | "all-levels"
    | "Beginner"
    | "Intermediate"
    | "Advanced"
    | "All Levels";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  category?: CategoryReference;
  instructor?: InstructorReference;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: BlockContent;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | SanityImageAssetReference
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | CategoryReference
  | InstructorReference
  | Course
  | Instructor
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course"] | order(_createdAt desc) {    _id,    _createdAt,    title,    slug,    summary,    coverImage,    level,    price,    "isPopular": coalesce(popular, isPopular, false),    popular,    studentCount,    category->{        _id,  title,  slug    },    instructor->{        _id,  name,  slug,  photo,  expertise    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  level:
    | "advanced"
    | "Advanced"
    | "All Levels"
    | "all-levels"
    | "beginner"
    | "Beginner"
    | "intermediate"
    | "Intermediate"
    | null;
  price: number | null;
  isPopular: boolean | false;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    expertise: Array<string> | null;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDuration: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: FEATURED_COURSES_QUERY
// Query: *[_type == "course" && (popular == true || isPopular == true || studentCount > 0)] | order(coalesce(popular, isPopular, false) desc, studentCount desc)[0...6] {    _id,    _createdAt,    title,    slug,    summary,    coverImage,    level,    price,    "isPopular": coalesce(popular, isPopular, false),    popular,    studentCount,    category->{        _id,  title,  slug    },    instructor->{        _id,  name,  slug,  photo,  expertise    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type FEATURED_COURSES_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  level:
    | "advanced"
    | "Advanced"
    | "All Levels"
    | "all-levels"
    | "beginner"
    | "Beginner"
    | "intermediate"
    | "Intermediate"
    | null;
  price: number | null;
  isPopular: boolean | false;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    expertise: Array<string> | null;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDuration: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    _createdAt,    title,    slug,    summary,    coverImage,    level,    price,    "isPopular": coalesce(popular, isPopular, false),    popular,    studentCount,    category->{      _id,      title,      slug,      description    },    instructor->{      _id,      name,      slug,      photo,      expertise,      bio    },    learningOutcomes[]{      _key,      icon,      title,      description    },    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        title,        slug,        duration,        "isFreePreview": coalesce(freePreview, isFreePreview, false),        freePreview,        studentCount      }    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  level:
    | "advanced"
    | "Advanced"
    | "All Levels"
    | "all-levels"
    | "beginner"
    | "Beginner"
    | "intermediate"
    | "Intermediate"
    | null;
  price: number | null;
  isPopular: boolean | false;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: Slug | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    expertise: Array<string> | null;
    bio: BlockContent | null;
  } | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
      duration: number | null;
      isFreePreview: boolean | false;
      freePreview: boolean | null;
      studentCount: number | null;
    }> | null;
  }> | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDuration: number | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $lessonSlug][0] {    _id,    title,    slug,    videoUrl,    thumbnail,    duration,    "isFreePreview": coalesce(freePreview, isFreePreview, false),    freePreview,    studentCount,    keyPoints,    proTip,    notes,    resources[]{      _key,      type,      title,      description,      url    },    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      slug,      instructor->{        _id,        name,        slug,        photo,        expertise      },      modules[]{        _key,        title,        summary,        lessons[]->{          _id,          title,          slug,          duration,          "isFreePreview": coalesce(freePreview, isFreePreview, false),          freePreview        }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  videoUrl: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  duration: number | null;
  isFreePreview: boolean | false;
  freePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  notes: BlockContent | null;
  resources: Array<{
    _key: string;
    type: "asset" | "docs" | "link" | "pdf" | "repo" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      expertise: Array<string> | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      summary: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: Slug | null;
        duration: number | null;
        isFreePreview: boolean | false;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(name asc) {    _id,    name,    slug,    photo,    expertise,    bio,    "courseCount": count(*[_type == "course" && instructor._ref == ^._id])  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  expertise: Array<string> | null;
  bio: BlockContent | null;
  courseCount: number;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    slug,    photo,    expertise,    bio,    "courses": *[_type == "course" && instructor._ref == ^._id] | order(_createdAt desc) {      _id,      title,      slug,      summary,      coverImage,      level,      price,      "isPopular": coalesce(popular, isPopular, false),      popular,      studentCount,      category->{          _id,  title,  slug      },      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[]),      "totalDuration": math::sum(modules[].lessons[]->duration)    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  expertise: Array<string> | null;
  bio: BlockContent | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    level:
      | "advanced"
      | "Advanced"
      | "All Levels"
      | "all-levels"
      | "beginner"
      | "Beginner"
      | "intermediate"
      | "Intermediate"
      | null;
    price: number | null;
    isPopular: boolean | false;
    popular: boolean | null;
    studentCount: number | null;
    category: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
    totalDuration: number | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug,    description,    "courseCount": count(*[_type == "course" && category._ref == ^._id])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  courseCount: number;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    slug,    description,    "courses": *[_type == "course" && category._ref == ^._id] | order(_createdAt desc) {      _id,      title,      slug,      summary,      coverImage,      level,      price,      "isPopular": coalesce(popular, isPopular, false),      popular,      studentCount,      instructor->{          _id,  name,  slug,  photo,  expertise      },      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[]),      "totalDuration": math::sum(modules[].lessons[]->duration)    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    level:
      | "advanced"
      | "Advanced"
      | "All Levels"
      | "all-levels"
      | "beginner"
      | "Beginner"
      | "intermediate"
      | "Intermediate"
      | null;
    price: number | null;
    isPopular: boolean | false;
    popular: boolean | null;
    studentCount: number | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      expertise: Array<string> | null;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
    totalDuration: number | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)][].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)][].slug.current
export type LESSON_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)][].slug.current
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)][].slug.current
export type CATEGORY_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course"] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    summary,\n    coverImage,\n    level,\n    price,\n    "isPopular": coalesce(popular, isPopular, false),\n    popular,\n    studentCount,\n    category->{\n      \n  _id,\n  title,\n  slug\n\n    },\n    instructor->{\n      \n  _id,\n  name,\n  slug,\n  photo,\n  expertise\n\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "totalDuration": math::sum(modules[].lessons[]->duration)\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && (popular == true || isPopular == true || studentCount > 0)] | order(coalesce(popular, isPopular, false) desc, studentCount desc)[0...6] {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    summary,\n    coverImage,\n    level,\n    price,\n    "isPopular": coalesce(popular, isPopular, false),\n    popular,\n    studentCount,\n    category->{\n      \n  _id,\n  title,\n  slug\n\n    },\n    instructor->{\n      \n  _id,\n  name,\n  slug,\n  photo,\n  expertise\n\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "totalDuration": math::sum(modules[].lessons[]->duration)\n  }\n': FEATURED_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    title,\n    slug,\n    summary,\n    coverImage,\n    level,\n    price,\n    "isPopular": coalesce(popular, isPopular, false),\n    popular,\n    studentCount,\n    category->{\n      _id,\n      title,\n      slug,\n      description\n    },\n    instructor->{\n      _id,\n      name,\n      slug,\n      photo,\n      expertise,\n      bio\n    },\n    learningOutcomes[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    modules[]{\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        title,\n        slug,\n        duration,\n        "isFreePreview": coalesce(freePreview, isFreePreview, false),\n        freePreview,\n        studentCount\n      }\n    },\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "totalDuration": math::sum(modules[].lessons[]->duration)\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $lessonSlug][0] {\n    _id,\n    title,\n    slug,\n    videoUrl,\n    thumbnail,\n    duration,\n    "isFreePreview": coalesce(freePreview, isFreePreview, false),\n    freePreview,\n    studentCount,\n    keyPoints,\n    proTip,\n    notes,\n    resources[]{\n      _key,\n      type,\n      title,\n      description,\n      url\n    },\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id,\n      title,\n      slug,\n      instructor->{\n        _id,\n        name,\n        slug,\n        photo,\n        expertise\n      },\n      modules[]{\n        _key,\n        title,\n        summary,\n        lessons[]->{\n          _id,\n          title,\n          slug,\n          duration,\n          "isFreePreview": coalesce(freePreview, isFreePreview, false),\n          freePreview\n        }\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor"] | order(name asc) {\n    _id,\n    name,\n    slug,\n    photo,\n    expertise,\n    bio,\n    "courseCount": count(*[_type == "course" && instructor._ref == ^._id])\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    slug,\n    photo,\n    expertise,\n    bio,\n    "courses": *[_type == "course" && instructor._ref == ^._id] | order(_createdAt desc) {\n      _id,\n      title,\n      slug,\n      summary,\n      coverImage,\n      level,\n      price,\n      "isPopular": coalesce(popular, isPopular, false),\n      popular,\n      studentCount,\n      category->{\n        \n  _id,\n  title,\n  slug\n\n      },\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[]),\n      "totalDuration": math::sum(modules[].lessons[]->duration)\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description,\n    "courseCount": count(*[_type == "course" && category._ref == ^._id])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    "courses": *[_type == "course" && category._ref == ^._id] | order(_createdAt desc) {\n      _id,\n      title,\n      slug,\n      summary,\n      coverImage,\n      level,\n      price,\n      "isPopular": coalesce(popular, isPopular, false),\n      popular,\n      studentCount,\n      instructor->{\n        \n  _id,\n  name,\n  slug,\n  photo,\n  expertise\n\n      },\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[]),\n      "totalDuration": math::sum(modules[].lessons[]->duration)\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)][].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)][].slug.current\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)][].slug.current\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)][].slug.current\n': CATEGORY_SLUGS_QUERY_RESULT;
  }
}
